# Generated by Django 2.0.1 on 2018-01-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usex',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='uemil',
            field=models.EmailField(default='', max_length=30),
        ),
    ]
