# Generated by Django 2.0.1 on 2018-02-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_goods', '0002_auto_20180202_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodinfo',
            name='gtype',
            field=models.ForeignKey(on_delete=None, to='sh_goods.TypeInfo'),
        ),
    ]
