# Generated by Django 2.0.1 on 2018-02-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_goods', '0005_auto_20180202_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lbsm', models.CharField(default='', max_length=20)),
                ('gpic', models.ImageField(upload_to='sh_goods')),
                ('gid', models.ForeignKey(on_delete=None, to='sh_goods.GoodInfo')),
            ],
        ),
    ]
